package parser

import (
	_ "embed"
	"fmt"
	"go/format"
	gotoken "go/token"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/carlmango11/gccarl/gccarl/parser/grammar"
	"github.com/carlmango11/gccarl/gccarl/tokens"
)

//go:embed runtime.txt
var runtimeTemplate string

// Generate writes a typed AST and grammar-specific parser. It needs no program input.
func (p *Parser) Generate(tokenInput io.Reader, outDir, packageName string) error {
	definitions, err := tokens.ParseDefinitions(tokenInput)
	if err != nil {
		return err
	}
	if err := validateGeneration(p.grammar, definitions, packageName); err != nil {
		return err
	}
	g := &Generator{grammar: p.grammar, packageName: packageName}
	g.generateTypes()
	var code strings.Builder
	fmt.Fprintf(&code, "package %s\nimport (\"fmt\"; \"io\"; \"sort\"; \"strings\"; \"github.com/carlmango11/gccarl/gccarl/tokens\")\n", packageName)
	for _, d := range definitions {
		if d.Regex != nil {
			code.WriteString("import \"regexp\"\n")
			break
		}
	}
	code.WriteString("var tokenDefinitions = []*tokens.TokenDef{\n")
	for _, d := range definitions {
		fmt.Fprintf(&code, "{Name:%q, Literal:%q", d.Name, d.Literal)
		if d.Regex != nil {
			fmt.Fprintf(&code, ", Regex:regexp.MustCompile(%q)", d.Regex.String())
		}
		code.WriteString("},\n")
	}
	code.WriteString("}\n")
	code.WriteString(runtimeTemplate)
	code.WriteString("\ntype parseState struct { tokens []*tokens.Token; farthest int; expected map[string]bool\n")
	for _, name := range sortedRules(p.grammar) {
		n := kebabToCamel(string(name))
		fmt.Fprintf(&code, "cache%s map[int][]parseMatch[*%s]\n", n, n)
	}
	code.WriteString("}\n")
	for _, name := range sortedRules(p.grammar) {
		g.generateParserRule(&code, name)
	}
	sources := []struct{ name, text string }{{"types.go", g.types.String()}, {"parser.go", code.String()}}
	for i := range sources {
		formatted, err := format.Source([]byte("// Code generated by gccarl parser; DO NOT EDIT.\n" + sources[i].text))
		if err != nil {
			return fmt.Errorf("generate %s: %w", sources[i].name, err)
		}
		sources[i].text = string(formatted)
	}
	dir := filepath.Join(outDir, packageName)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	for _, source := range sources {
		if err := os.WriteFile(filepath.Join(dir, source.name), []byte(source.text), 0644); err != nil {
			return err
		}
	}
	return nil
}

func sortedRules(rules map[grammar.RuleName]*grammar.Rule) []grammar.RuleName {
	names := make([]grammar.RuleName, 0, len(rules))
	for name := range rules {
		names = append(names, name)
	}
	sort.Slice(names, func(i, j int) bool { return names[i] < names[j] })
	return names
}

func partFields(parts []*grammar.Part) []string {
	names := make([]string, len(parts))
	counts := map[string]int{}
	for i, p := range parts {
		names[i] = string(p.Token)
		if p.IsRule() {
			names[i] = optionRuleFieldName(p.Rule)
		}
		counts[names[i]]++
	}
	seen := map[string]int{}
	for i, name := range names {
		if counts[name] > 1 {
			names[i] = fmt.Sprintf("%s%d", name, seen[name])
			seen[name]++
		}
	}
	return names
}

func partType(part *grammar.Part) string {
	name := string(part.Token)
	if part.IsRule() {
		name = "*" + optionRuleFieldName(part.Rule)
	}
	if part.Cardinality == grammar.CardMultiple || part.Cardinality == grammar.CardOneOrMore {
		name = "[]" + name
	}
	return name
}

func (g *Generator) generateParserRule(code *strings.Builder, rule grammar.RuleName) {
	name := kebabToCamel(string(rule))
	fmt.Fprintf(code, "func (p *parseState) parse%s(pos int) []parseMatch[*%s] {\n", name, name)
	fmt.Fprintf(code, "if matches, ok := p.cache%s[pos]; ok { return matches }; var matches []parseMatch[*%s]\n", name, name)
	for _, option := range g.grammar[rule].Options {
		typ := optionStruct(rule, option.Name)
		fields := partFields(option.Parts)
		fmt.Fprintf(code, "{ states := []parseMatch[%s]{{end:pos}}\n", typ)
		for i, part := range option.Parts {
			var parse string
			if part.IsRule() {
				parse = "p.parse" + optionRuleFieldName(part.Rule)
			} else {
				parse = fmt.Sprintf("func(pos int) []parseMatch[%s] { return matchToken[%s](p,pos,%q) }", part.Token, part.Token, part.Token)
			}
			switch part.Cardinality {
			case grammar.CardZeroOrOne:
				parse = "optionalMatch(" + parse + ")"
			case grammar.CardMultiple:
				parse = "repeatedMatches(" + parse + ",0)"
			case grammar.CardOneOrMore:
				parse = "repeatedMatches(" + parse + ",1)"
			}
			fmt.Fprintf(code, "states = extendMatches(states, %s, func(value *%s, child %s) { value.%s = child })\n", parse, typ, partType(part), fields[i])
		}
		fmt.Fprintf(code, "for _, state := range states { value := state.value; matches = append(matches, parseMatch[*%s]{value:&%s{Type:%s, %s:&value},end:state.end}) }\n}\n", name, name, typeEnumField(rule, option.Name), optionField(option.Name))
	}
	fmt.Fprintf(code, "if p.cache%s == nil { p.cache%s = map[int][]parseMatch[*%s]{} }; p.cache%s[pos] = matches; return matches\n}\n", name, name, name, name)
}

func validateGeneration(rules map[grammar.RuleName]*grammar.Rule, definitions []*tokens.TokenDef, packageName string) error {
	if !gotoken.IsIdentifier(packageName) || packageName == "_" {
		return fmt.Errorf("invalid package name %q", packageName)
	}
	if rules["main"] == nil {
		return fmt.Errorf("grammar requires a main rule")
	}
	symbols := map[string]bool{"Parse": true, "parseState": true, "parseMatch": true, "tokenDefinitions": true, "matchToken": true, "extendMatches": true, "optionalMatch": true, "repeatedMatches": true, "tokens": true, "fmt": true, "io": true, "sort": true, "strings": true, "regexp": true}
	add := func(name string) error {
		if !gotoken.IsIdentifier(name) || name == "_" {
			return fmt.Errorf("invalid generated identifier %q", name)
		}
		if symbols[name] {
			return fmt.Errorf("duplicate generated identifier %q", name)
		}
		symbols[name] = true
		return nil
	}
	known := map[tokens.Name]bool{}
	for _, d := range definitions {
		if known[tokens.Name(d.Name)] {
			return fmt.Errorf("duplicate token %q", d.Name)
		}
		known[tokens.Name(d.Name)] = true
	}
	used := map[tokens.Name]bool{}
	for _, name := range sortedRules(rules) {
		if err := add(kebabToCamel(string(name))); err != nil {
			return err
		}
		if err := add(typeEnumType(name)); err != nil {
			return err
		}
		options := map[string]bool{"Type": true}
		for _, option := range rules[name].Options {
			field := optionField(option.Name)
			if options[field] {
				return fmt.Errorf("duplicate option field %s.%s", name, field)
			}
			options[field] = true
			if err := add(optionStruct(name, option.Name)); err != nil {
				return err
			}
			if err := add(typeEnumField(name, option.Name)); err != nil {
				return err
			}
			fields := map[string]bool{}
			for _, field := range partFields(option.Parts) {
				if !gotoken.IsIdentifier(field) || fields[field] {
					return fmt.Errorf("invalid or duplicate field %s.%s", name, field)
				}
				fields[field] = true
			}
			for _, part := range option.Parts {
				if part.IsRule() {
					continue
				}
				if !known[part.Token] {
					return fmt.Errorf("undefined token %q in rule %q", part.Token, name)
				}
				used[part.Token] = true
			}
		}
	}
	for name := range used {
		if err := add(string(name)); err != nil {
			return err
		}
	}
	nullable := map[grammar.RuleName]bool{}
	for changed := true; changed; {
		changed = false
		for name, rule := range rules {
			if nullable[name] {
				continue
			}
			for _, option := range rule.Options {
				empty := true
				for _, part := range option.Parts {
					if part.Cardinality == grammar.CardMultiple || part.Cardinality == grammar.CardZeroOrOne {
						continue
					}
					if !part.IsRule() || !nullable[part.Rule] {
						empty = false
						break
					}
				}
				if empty {
					nullable[name] = true
					changed = true
					break
				}
			}
		}
	}
	for name, rule := range rules {
		for _, option := range rule.Options {
			for _, part := range option.Parts {
				if (part.Cardinality == grammar.CardMultiple || part.Cardinality == grammar.CardOneOrMore) && nullable[part.Rule] {
					return fmt.Errorf("rule %q repeats nullable rule %q", name, part.Rule)
				}
			}
		}
	}
	active, done := map[grammar.RuleName]bool{}, map[grammar.RuleName]bool{}
	var visit func(grammar.RuleName) error
	visit = func(name grammar.RuleName) error {
		if active[name] {
			return fmt.Errorf("left recursion involving rule %q is unsupported", name)
		}
		if done[name] {
			return nil
		}
		active[name] = true
		for _, option := range rules[name].Options {
			for _, part := range option.Parts {
				if part.IsRule() {
					if err := visit(part.Rule); err != nil {
						return err
					}
				}
				if part.Cardinality != grammar.CardMultiple && part.Cardinality != grammar.CardZeroOrOne && !nullable[part.Rule] {
					break
				}
			}
		}
		active[name] = false
		done[name] = true
		return nil
	}
	for _, name := range sortedRules(rules) {
		if err := visit(name); err != nil {
			return err
		}
	}
	return nil
}
